fix(godwoken_service): Error: this.indexer not found. <= Failed to create RocksDB directory: `Os { code: 13, kind: PermissionDenied, message: \"Permission denied\" }
$ yarn workspace @godwoken-examples/runner prepare-money
$ LUMOS_CONFIG_FILE=./configs/lumos-config.json MODE=docker-compose ts-node-dev ./src/prepare_money.ts
[INFO] 10:09:12 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.4)
start..
Error: this.indexer not found.
    at Api.checkCkbBalance (/godwoken-examples/packages/runner/src/api.ts:1137:13)
    at Object.run (/godwoken-examples/packages/runner/src/prepare_money.ts:25:36)
    at Object.<anonymous> (/godwoken-examples/packages/runner/src/prepare_money.ts:50:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/godwoken-examples/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-15625269222695226.js:69:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at require.extensions..jsx.require.extensions..js (/tmp/ts-node-dev-hook-15625269222695226.js:114:20)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-15625269222695226.js:71:20)
    at Object.nodeDevHook [as .ts] (/godwoken-examples/node_modules/ts-node-dev/lib/hook.js:63:13)
(node:96) UnhandledPromiseRejectionWarning: Error: internal error in Neon module: Failed to open rocksdb: Error { message: "Failed to create RocksDB directory: `Os { code: 13, kind: PermissionDenied, message: \"Permission denied\" }`." }

https://github.com/RetricSu/godwoken-kicker/pull/18#issuecomment-839663249